language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx

env:
  - FLAGS=
  - FLAGS="--features glium-support"
script:
  - cargo build $(echo $FLAGS)
  - cargo test  $(echo $FLAGS)


notifications:
  irc:
    nick: xmath
    channels:
      - irc.uriirc.org:16667#hyeon
    template:
      - "#%{build_number} %{result}, %{build_url}"
    skip_join: true
